# Generated by Django 4.0.5 on 2022-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=80)),
                ('description', models.TextField(help_text='description')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='end time', null=True)),
                ('is_archive', models.BooleanField(default=False, help_text='Is this timer archived?')),
                ('short_link', models.CharField(blank=True, default='', help_text='timer short link', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='create time')),
                ('updated', models.DateTimeField(auto_now=True, help_text='update time')),
            ],
        ),
    ]
