# Generated by Django 4.0.5 on 2022-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_todo_alter_timer_short_link_timer_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='todo',
            field=models.ManyToManyField(blank=True, null=True, related_name='todo', to='api_v1.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(help_text='Is this ToDo done?'),
        ),
    ]
